name: Deploy to Azure VMs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_VM1:
    runs-on: ubuntu-latest

    env:
      REMOTE_IP: "13.90.101.59"

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.REMOTE_IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.VM_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Stop Gunicorn
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'cd /home/hcps-duttav && sudo pkill -9 gunicorn || true'

      - name: Clone Repository and Setup Environment
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'cd /home/hcps-duttav && sudo rm -rf Fredclick && sudo git clone https://github.com/vihdutta/Fredclick && cd Fredclick && sudo apt update && sudo apt install nano git python3-pip python3-venv -y && sudo python3 -m venv .venv && sudo chown -R $(whoami) .venv && source .venv/bin/activate && sudo pip install -r requirements.txt && pip install gunicorn && sudo apt install python3 -y'

      - name: Create vm_info.json
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'cd /home/hcps-duttav/Fredclick && sudo chmod +x get_vm_info.sh && sudo ./get_vm_info.sh'

      - name: Create .env file
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'sudo -i bash -c "cd /home/hcps-duttav/Fredclick && echo \"MONGO_URI= ${{ secrets.MONGO_URI }}\" > .env && echo \"SECRET_KEY=${{ secrets.SECRET_KEY }}\" >> .env"'

      - name: Start Gunicorn
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'cd /home/hcps-duttav/Fredclick && source .venv/bin/activate && export WORKERS=$(($(nproc)*2 + 2)) && sudo gunicorn -w $WORKERS -b 0.0.0.0:80 app:app --daemon'

  deploy_VM2:
    runs-on: ubuntu-latest

    env:
      REMOTE_IP: "40.71.248.101"

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.REMOTE_IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.VM_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Stop Gunicorn
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'cd /home/hcps-duttav && sudo pkill -9 gunicorn || true'

      - name: Clone Repository and Setup Environment
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'cd /home/hcps-duttav && sudo rm -rf Fredclick && sudo git clone https://github.com/vihdutta/Fredclick && cd Fredclick && sudo apt update && sudo apt install nano git python3-pip python3-venv -y && sudo python3 -m venv .venv && sudo chown -R $(whoami) .venv && source .venv/bin/activate && sudo pip install -r requirements.txt && pip install gunicorn && sudo apt install python3 -y'

      - name: Create vm_info.json
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'cd /home/hcps-duttav/Fredclick && sudo chmod +x get_vm_info.sh && sudo ./get_vm_info.sh'

      - name: Create .env file
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'sudo -i bash -c "cd /home/hcps-duttav/Fredclick && echo \"MONGO_URI= ${{ secrets.MONGO_URI }}\" > .env && echo \"SECRET_KEY=${{ secrets.SECRET_KEY }}\" >> .env"'

      - name: Start Gunicorn
        run: |
          ssh -i ~/.ssh/id_rsa vihdutta@${{ env.REMOTE_IP }} 'cd /home/hcps-duttav/Fredclick && source .venv/bin/activate && export WORKERS=$(($(nproc)*2 + 2)) && sudo gunicorn -w $WORKERS -b 0.0.0.0:80 app:app --daemon'
